# Generated by Django 6.0.7 on 2026-08-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='second last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='second name'),
        ),
    ]
