# Generated by Django 6.0.7 on 2026-08-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0004_seed_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='payment_pin_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='payment PIN hash'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='students', to='catalog.allergen', verbose_name='allergies'),
        ),
    ]
