# Generated by Django 6.0.7 on 2026-08-27 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_parentprofile_payment_pin_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_enabled', models.BooleanField(default=False, verbose_name='daily limit enabled')),
                ('daily_limit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='daily limit amount')),
                ('allowed_days_enabled', models.BooleanField(default=False, verbose_name='allowed days enabled')),
                ('allowed_days', models.JSONField(default=list, help_text='List of integers (0=Monday, 6=Sunday)', verbose_name='allowed days')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental_control', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'parental control',
                'verbose_name_plural': 'parental controls',
            },
        ),
    ]
