# Generated by Django 6.0.7 on 2026-09-11 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_parentalcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_embedding', models.BinaryField(verbose_name='encrypted embedding')),
                ('nonce', models.BinaryField(max_length=12, verbose_name='encryption nonce')),
                ('tag', models.BinaryField(max_length=16, verbose_name='encryption auth tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user biometric',
                'verbose_name_plural': 'user biometrics',
            },
        ),
    ]
