# Generated by Django 6.0.7 on 2026-10-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userbiometric'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userallergy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userallergy',
            name='allergen',
        ),
        migrations.RemoveField(
            model_name='userallergy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
        migrations.DeleteModel(
            name='UserAllergy',
        ),
    ]