# Generated by Django 6.0.7 on 2026-08-27 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_menuitem_category_menuitem_image'),
        ('users', '0006_parentalcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_orders', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'pre-order',
                'verbose_name_plural': 'pre-orders',
            },
        ),
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price at purchase')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.menuitem')),
                ('pre_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.preorder')),
            ],
        ),
    ]
