# Generated by Django 6.0.7 on 2026-08-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/menu_items/', verbose_name='image'),
        ),
    ]
