# Generated by Django 6.0.7 on 2026-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_menuitem_category_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='catalog.allergen'),
        ),
    ]
