# Generated by Django 6.0.7 on 2026-09-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ingredient_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergens_reviewed',
            field=models.BooleanField(default=False, help_text="True once an admin has explicitly confirmed this ingredient's allergens (even confirming it has none). Stays False for newly created ingredients until someone reviews it — this is what MenuItemSerializer checks before allowing a product to be saved with this ingredient.", verbose_name='allergens reviewed'),
        ),
    ]
